In [22]:
from sklearn.neighbors import NearestNeighbors
import pandas as pd
import numpy as np

In [25]:
df = pd.read_csv('sample.csv' ,index_col='UserID')
df.fillna(0, inplace=True)
print(df.head())

        movie1  movie2  movie3  movie4  movie5  ...  movie8  movie9  movie10  movie11  movie12
UserID                                          ...                                           
1          1.0     0.0     3.0     4.0     5.0  ...     8.0     9.0     10.0       11     12.0
2          1.0     0.0     3.0     0.0     0.0  ...     0.0     5.0      0.0        4      0.0
3          0.0     0.0     5.0     4.0     0.0  ...     0.0     0.0      2.0        1      3.0
4          2.0     4.0     0.0     1.0     2.0  ...     0.0     4.0      3.0        5      0.0
5          0.0     2.0     4.0     0.0     5.0  ...     4.0     0.0      0.0        2      0.0

[5 rows x 12 columns]


In [26]:
neighbor = 5
knn = NearestNeighbors(metric='cosine' , algorithm='brute')
knn.fit(df.values)
distance , indices = knn.kneighbors(df.values, n_neighbors=neighbor)

In [17]:
distance

array([[0.00000000e+00, 2.30690347e-01, 3.08468366e-01, 3.21732223e-01,
        4.11055195e-01],
       [1.11022302e-16, 1.05369922e-01, 4.17807435e-01, 4.74342517e-01,
        5.22433067e-01],
       [2.22044605e-16, 1.60657276e-01, 3.29922116e-01, 4.11664422e-01,
        4.28513111e-01],
       [0.00000000e+00, 3.03835808e-01, 3.21732223e-01, 4.12430349e-01,
        4.17636465e-01],
       [0.00000000e+00, 1.45957519e-01, 2.05564973e-01, 3.48537658e-01,
        4.32582961e-01],
       [1.11022302e-16, 1.99038269e-01, 3.27172586e-01, 3.29922116e-01,
        3.48537658e-01],
       [1.11022302e-16, 1.45957519e-01, 1.69743306e-01, 3.27172586e-01,
        3.44576410e-01],
       [1.11022302e-16, 1.05369922e-01, 3.45828863e-01, 4.12430349e-01,
        4.41122707e-01],
       [0.00000000e+00, 1.60657276e-01, 2.30690347e-01, 2.48746866e-01,
        3.99105441e-01],
       [0.00000000e+00, 2.48746866e-01, 2.84011851e-01, 3.03835808e-01,
        3.08468366e-01],
       [0.00000000e+00, 1.6974

In [28]:
indices

array([[ 0,  8,  9,  3,  5],
       [ 1,  7,  0,  3,  6],
       [ 2,  8,  5,  0,  9],
       [ 3,  9,  0,  7, 10],
       [ 4,  6, 10,  5,  9],
       [ 5, 10,  6,  2,  4],
       [ 6,  4, 10,  5,  9],
       [ 7,  1,  6,  3,  9],
       [ 8,  2,  0,  9,  5],
       [ 9,  8, 10,  3,  0],
       [10,  6,  5,  4,  9]])

In [27]:
similarity = 1 - distance
similarity

array([[1.        , 0.76930965, 0.69153163, 0.67826778, 0.58894481],
       [1.        , 0.89463008, 0.58219257, 0.52565748, 0.47756693],
       [1.        , 0.83934272, 0.67007788, 0.58833558, 0.57148689],
       [1.        , 0.69616419, 0.67826778, 0.58756965, 0.58236353],
       [1.        , 0.85404248, 0.79443503, 0.65146234, 0.56741704],
       [1.        , 0.80096173, 0.67282741, 0.67007788, 0.65146234],
       [1.        , 0.85404248, 0.83025669, 0.67282741, 0.65542359],
       [1.        , 0.89463008, 0.65417114, 0.58756965, 0.55887729],
       [1.        , 0.83934272, 0.76930965, 0.75125313, 0.60089456],
       [1.        , 0.75125313, 0.71598815, 0.69616419, 0.69153163],
       [1.        , 0.83025669, 0.80096173, 0.79443503, 0.71598815]])

In [32]:
def predict_rating(user_id, movie_id):
    user_index = df.index.get_loc(user_id)
    movie_index = df.columns.get_loc(movie_id)  # Assuming movie_id is a column name

    # Get the neighbors for the given user
    neighbors = indices[user_index]

    # Calculate the weighted average of ratings from similar users for the movie
    weighted_sum = 0
    similarity_sum = 0

    for neighbor_index in neighbors:
        if df.iloc[neighbor_index, movie_index] != 0: # Check for rating from neighbor
          weighted_sum += similarity[user_index, np.where(neighbors == neighbor_index)[0][0]] * df.iloc[neighbor_index, movie_index]
          similarity_sum += similarity[user_index, np.where(neighbors == neighbor_index)[0][0]]

    if similarity_sum == 0:
        return 0  # Or handle the case where no similar users rated the movie
    else:
        return weighted_sum / similarity_sum


# Predict the rating for user1 for movie2
user1_movie2_rating = predict_rating(2, 'movie8')
print(f"Predicted rating for user 1 for movie 2: {user1_movie2_rating}")


Predicted rating for user 1 for movie 2: 5.296177479644565
